# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/salaadas/Programming/pong-with-crt

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/salaadas/Programming/pong-with-crt

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/salaadas/Programming/pong-with-crt/CMakeFiles /home/salaadas/Programming/pong-with-crt//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/salaadas/Programming/pong-with-crt/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named game_debug

# Build rule for target.
game_debug: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 game_debug
.PHONY : game_debug

# fast build rule for target.
game_debug/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/build
.PHONY : game_debug/fast

catalog.o: catalog.cpp.o
.PHONY : catalog.o

# target to build an object file
catalog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/catalog.cpp.o
.PHONY : catalog.cpp.o

catalog.i: catalog.cpp.i
.PHONY : catalog.i

# target to preprocess a source file
catalog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/catalog.cpp.i
.PHONY : catalog.cpp.i

catalog.s: catalog.cpp.s
.PHONY : catalog.s

# target to generate assembly for a file
catalog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/catalog.cpp.s
.PHONY : catalog.cpp.s

common.o: common.cpp.o
.PHONY : common.o

# target to build an object file
common.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/common.cpp.o
.PHONY : common.cpp.o

common.i: common.cpp.i
.PHONY : common.i

# target to preprocess a source file
common.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/common.cpp.i
.PHONY : common.cpp.i

common.s: common.cpp.s
.PHONY : common.s

# target to generate assembly for a file
common.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/common.cpp.s
.PHONY : common.cpp.s

compiled_header_libs.o: compiled_header_libs.cpp.o
.PHONY : compiled_header_libs.o

# target to build an object file
compiled_header_libs.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/compiled_header_libs.cpp.o
.PHONY : compiled_header_libs.cpp.o

compiled_header_libs.i: compiled_header_libs.cpp.i
.PHONY : compiled_header_libs.i

# target to preprocess a source file
compiled_header_libs.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/compiled_header_libs.cpp.i
.PHONY : compiled_header_libs.cpp.i

compiled_header_libs.s: compiled_header_libs.cpp.s
.PHONY : compiled_header_libs.s

# target to generate assembly for a file
compiled_header_libs.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/compiled_header_libs.cpp.s
.PHONY : compiled_header_libs.cpp.s

draw.o: draw.cpp.o
.PHONY : draw.o

# target to build an object file
draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/draw.cpp.o
.PHONY : draw.cpp.o

draw.i: draw.cpp.i
.PHONY : draw.i

# target to preprocess a source file
draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/draw.cpp.i
.PHONY : draw.cpp.i

draw.s: draw.cpp.s
.PHONY : draw.s

# target to generate assembly for a file
draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/draw.cpp.s
.PHONY : draw.cpp.s

events.o: events.cpp.o
.PHONY : events.o

# target to build an object file
events.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/events.cpp.o
.PHONY : events.cpp.o

events.i: events.cpp.i
.PHONY : events.i

# target to preprocess a source file
events.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/events.cpp.i
.PHONY : events.cpp.i

events.s: events.cpp.s
.PHONY : events.s

# target to generate assembly for a file
events.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/events.cpp.s
.PHONY : events.cpp.s

file_utils.o: file_utils.cpp.o
.PHONY : file_utils.o

# target to build an object file
file_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/file_utils.cpp.o
.PHONY : file_utils.cpp.o

file_utils.i: file_utils.cpp.i
.PHONY : file_utils.i

# target to preprocess a source file
file_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/file_utils.cpp.i
.PHONY : file_utils.cpp.i

file_utils.s: file_utils.cpp.s
.PHONY : file_utils.s

# target to generate assembly for a file
file_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/file_utils.cpp.s
.PHONY : file_utils.cpp.s

font.o: font.cpp.o
.PHONY : font.o

# target to build an object file
font.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/font.cpp.o
.PHONY : font.cpp.o

font.i: font.cpp.i
.PHONY : font.i

# target to preprocess a source file
font.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/font.cpp.i
.PHONY : font.cpp.i

font.s: font.cpp.s
.PHONY : font.s

# target to generate assembly for a file
font.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/font.cpp.s
.PHONY : font.cpp.s

hash.o: hash.cpp.o
.PHONY : hash.o

# target to build an object file
hash.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/hash.cpp.o
.PHONY : hash.cpp.o

hash.i: hash.cpp.i
.PHONY : hash.i

# target to preprocess a source file
hash.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/hash.cpp.i
.PHONY : hash.cpp.i

hash.s: hash.cpp.s
.PHONY : hash.s

# target to generate assembly for a file
hash.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/hash.cpp.s
.PHONY : hash.cpp.s

hotloader.o: hotloader.cpp.o
.PHONY : hotloader.o

# target to build an object file
hotloader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/hotloader.cpp.o
.PHONY : hotloader.cpp.o

hotloader.i: hotloader.cpp.i
.PHONY : hotloader.i

# target to preprocess a source file
hotloader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/hotloader.cpp.i
.PHONY : hotloader.cpp.i

hotloader.s: hotloader.cpp.s
.PHONY : hotloader.s

# target to generate assembly for a file
hotloader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/hotloader.cpp.s
.PHONY : hotloader.cpp.s

hud.o: hud.cpp.o
.PHONY : hud.o

# target to build an object file
hud.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/hud.cpp.o
.PHONY : hud.cpp.o

hud.i: hud.cpp.i
.PHONY : hud.i

# target to preprocess a source file
hud.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/hud.cpp.i
.PHONY : hud.cpp.i

hud.s: hud.cpp.s
.PHONY : hud.s

# target to generate assembly for a file
hud.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/hud.cpp.s
.PHONY : hud.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/main.cpp.s
.PHONY : main.cpp.s

newstring.o: newstring.cpp.o
.PHONY : newstring.o

# target to build an object file
newstring.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/newstring.cpp.o
.PHONY : newstring.cpp.o

newstring.i: newstring.cpp.i
.PHONY : newstring.i

# target to preprocess a source file
newstring.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/newstring.cpp.i
.PHONY : newstring.cpp.i

newstring.s: newstring.cpp.s
.PHONY : newstring.s

# target to generate assembly for a file
newstring.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/newstring.cpp.s
.PHONY : newstring.cpp.s

opengl.o: opengl.cpp.o
.PHONY : opengl.o

# target to build an object file
opengl.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/opengl.cpp.o
.PHONY : opengl.cpp.o

opengl.i: opengl.cpp.i
.PHONY : opengl.i

# target to preprocess a source file
opengl.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/opengl.cpp.i
.PHONY : opengl.cpp.i

opengl.s: opengl.cpp.s
.PHONY : opengl.s

# target to generate assembly for a file
opengl.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/opengl.cpp.s
.PHONY : opengl.cpp.s

path_utils.o: path_utils.cpp.o
.PHONY : path_utils.o

# target to build an object file
path_utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/path_utils.cpp.o
.PHONY : path_utils.cpp.o

path_utils.i: path_utils.cpp.i
.PHONY : path_utils.i

# target to preprocess a source file
path_utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/path_utils.cpp.i
.PHONY : path_utils.cpp.i

path_utils.s: path_utils.cpp.s
.PHONY : path_utils.s

# target to generate assembly for a file
path_utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/path_utils.cpp.s
.PHONY : path_utils.cpp.s

pong.o: pong.cpp.o
.PHONY : pong.o

# target to build an object file
pong.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/pong.cpp.o
.PHONY : pong.cpp.o

pong.i: pong.cpp.i
.PHONY : pong.i

# target to preprocess a source file
pong.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/pong.cpp.i
.PHONY : pong.cpp.i

pong.s: pong.cpp.s
.PHONY : pong.s

# target to generate assembly for a file
pong.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/pong.cpp.s
.PHONY : pong.cpp.s

pool.o: pool.cpp.o
.PHONY : pool.o

# target to build an object file
pool.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/pool.cpp.o
.PHONY : pool.cpp.o

pool.i: pool.cpp.i
.PHONY : pool.i

# target to preprocess a source file
pool.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/pool.cpp.i
.PHONY : pool.cpp.i

pool.s: pool.cpp.s
.PHONY : pool.s

# target to generate assembly for a file
pool.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/pool.cpp.s
.PHONY : pool.cpp.s

shader_catalog.o: shader_catalog.cpp.o
.PHONY : shader_catalog.o

# target to build an object file
shader_catalog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/shader_catalog.cpp.o
.PHONY : shader_catalog.cpp.o

shader_catalog.i: shader_catalog.cpp.i
.PHONY : shader_catalog.i

# target to preprocess a source file
shader_catalog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/shader_catalog.cpp.i
.PHONY : shader_catalog.cpp.i

shader_catalog.s: shader_catalog.cpp.s
.PHONY : shader_catalog.s

# target to generate assembly for a file
shader_catalog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/shader_catalog.cpp.s
.PHONY : shader_catalog.cpp.s

string_builder.o: string_builder.cpp.o
.PHONY : string_builder.o

# target to build an object file
string_builder.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/string_builder.cpp.o
.PHONY : string_builder.cpp.o

string_builder.i: string_builder.cpp.i
.PHONY : string_builder.i

# target to preprocess a source file
string_builder.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/string_builder.cpp.i
.PHONY : string_builder.cpp.i

string_builder.s: string_builder.cpp.s
.PHONY : string_builder.s

# target to generate assembly for a file
string_builder.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/string_builder.cpp.s
.PHONY : string_builder.cpp.s

table.o: table.cpp.o
.PHONY : table.o

# target to build an object file
table.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/table.cpp.o
.PHONY : table.cpp.o

table.i: table.cpp.i
.PHONY : table.i

# target to preprocess a source file
table.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/table.cpp.i
.PHONY : table.cpp.i

table.s: table.cpp.s
.PHONY : table.s

# target to generate assembly for a file
table.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/table.cpp.s
.PHONY : table.cpp.s

texture.o: texture.cpp.o
.PHONY : texture.o

# target to build an object file
texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/texture.cpp.o
.PHONY : texture.cpp.o

texture.i: texture.cpp.i
.PHONY : texture.i

# target to preprocess a source file
texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/texture.cpp.i
.PHONY : texture.cpp.i

texture.s: texture.cpp.s
.PHONY : texture.s

# target to generate assembly for a file
texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/texture.cpp.s
.PHONY : texture.cpp.s

texture_catalog.o: texture_catalog.cpp.o
.PHONY : texture_catalog.o

# target to build an object file
texture_catalog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/texture_catalog.cpp.o
.PHONY : texture_catalog.cpp.o

texture_catalog.i: texture_catalog.cpp.i
.PHONY : texture_catalog.i

# target to preprocess a source file
texture_catalog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/texture_catalog.cpp.i
.PHONY : texture_catalog.cpp.i

texture_catalog.s: texture_catalog.cpp.s
.PHONY : texture_catalog.s

# target to generate assembly for a file
texture_catalog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/texture_catalog.cpp.s
.PHONY : texture_catalog.cpp.s

time_info.o: time_info.cpp.o
.PHONY : time_info.o

# target to build an object file
time_info.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/time_info.cpp.o
.PHONY : time_info.cpp.o

time_info.i: time_info.cpp.i
.PHONY : time_info.i

# target to preprocess a source file
time_info.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/time_info.cpp.i
.PHONY : time_info.cpp.i

time_info.s: time_info.cpp.s
.PHONY : time_info.s

# target to generate assembly for a file
time_info.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/game_debug.dir/build.make CMakeFiles/game_debug.dir/time_info.cpp.s
.PHONY : time_info.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... game_debug"
	@echo "... catalog.o"
	@echo "... catalog.i"
	@echo "... catalog.s"
	@echo "... common.o"
	@echo "... common.i"
	@echo "... common.s"
	@echo "... compiled_header_libs.o"
	@echo "... compiled_header_libs.i"
	@echo "... compiled_header_libs.s"
	@echo "... draw.o"
	@echo "... draw.i"
	@echo "... draw.s"
	@echo "... events.o"
	@echo "... events.i"
	@echo "... events.s"
	@echo "... file_utils.o"
	@echo "... file_utils.i"
	@echo "... file_utils.s"
	@echo "... font.o"
	@echo "... font.i"
	@echo "... font.s"
	@echo "... hash.o"
	@echo "... hash.i"
	@echo "... hash.s"
	@echo "... hotloader.o"
	@echo "... hotloader.i"
	@echo "... hotloader.s"
	@echo "... hud.o"
	@echo "... hud.i"
	@echo "... hud.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... newstring.o"
	@echo "... newstring.i"
	@echo "... newstring.s"
	@echo "... opengl.o"
	@echo "... opengl.i"
	@echo "... opengl.s"
	@echo "... path_utils.o"
	@echo "... path_utils.i"
	@echo "... path_utils.s"
	@echo "... pong.o"
	@echo "... pong.i"
	@echo "... pong.s"
	@echo "... pool.o"
	@echo "... pool.i"
	@echo "... pool.s"
	@echo "... shader_catalog.o"
	@echo "... shader_catalog.i"
	@echo "... shader_catalog.s"
	@echo "... string_builder.o"
	@echo "... string_builder.i"
	@echo "... string_builder.s"
	@echo "... table.o"
	@echo "... table.i"
	@echo "... table.s"
	@echo "... texture.o"
	@echo "... texture.i"
	@echo "... texture.s"
	@echo "... texture_catalog.o"
	@echo "... texture_catalog.i"
	@echo "... texture_catalog.s"
	@echo "... time_info.o"
	@echo "... time_info.i"
	@echo "... time_info.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

